metis_default_server:
  type: string
  label: Default server
metis_force_ssl:
  type: boolean
  label: Force SSL
username:
  type: string
  label: SOAP service username
password:
  type: string
  label: SOAP service password
field.value.metis:
  type: mapping
  label: Default value
  mapping:
    code_public:
      type: string
      label: Public code
    code_private:
      type: string
      label: Private code
    show:
      type: boolean
      label: Show
    server:
      type: string
      label: Server
